### ISSUE TITLE
Subject number is deleted in some plots/data

### ISSUE THREAD

**Issue by mpcoll** [crisglav/eeg-pipeline#10]
In the plot functions, the section below deletes the participant number in some figures in our data since we have 8 tasks/participant, and the last figure only includes tasks from the same participant. This gets confusing since the participant field is present in some figures/data and not others. I would suggest removing this or at least not saving the truncated ids to the .mat files to keep the same fields in all figures/data.

```
 % same (e.g. if all sessions are ses-1)
    splitted_ids = cellfun(@(x) strsplit(x,'_'),s_ids(bmask),'UniformOutput',false);
    splitted_ids = vertcat(splitted_ids{:});
    mask = ones(1,size(splitted_ids,2));
```

**Comment by crisglav** [comment]
Thanks for the suggestion. I removed the information that belonged to the same participant/task if it was all the same for the recordings to improve the readibility of the plots, but I understand that this can be confusing in some cases. I followed your recommendation and the full id is saved now in the .mat files.

Best,
Cristina
