### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Maari13** [crisglav/eeg-pipeline#11]
Tried running the pipeline with the demo dataset, however, Matlab gives the error:

Out of memory. The likely cause is an infinite recursion within the program.

Error in bids_importjson/isTopLevel (line 83)
            curpath = fileparts(curfile);

When exploring the code and the behavior of the program, I see that the function "function res = isTopLevel(curfile)" iterates up the catalogue tree, past the folder which has the README file in it (I assume finding this file was supposed to be the stopping condition) and the the very root folder (C:\) where it keeps iterating until running out of memory.

I use the newest version of Matlab and the other programs involved.

**Comment by Maari13** [comment]
This problem can actually be easily solved. The line in code (bids_importjson/isTopLevel (line 83)) 
if ~files(f).isdir && strcmp(files(f).name, 'README')
checks for exact match of a file named 'README', however, the README file in demo data has an extension 'txt'. Hence the line in code needs to be modified accordingly: 
if ~files(f).isdir && strcmp(files(f).name, 'README.txt')

**Comment by AI-Hans** [comment]
Hi there, I'm wondering if you've resolved the issue and how you managed to adjust the code to avoid infinite recursion and successfully run the pipeline?

**Comment by Maari13** [comment]
The demo dataset contains a file "README.txt" in the top level folder, however the code in bids_importjson.m checks for an exact match of a filename "README" (not allowing for any file extensions). Finding the file with such a name is supposed to indicate that the recursion through the folder tree has reached the top level. I fixed the problem by changing the corresponding line in the code (function isTopLevel(), line 95) as follows:

if ~files(f).isdir && strcmp(files(f).name, 'README.txt')
