### ISSUE TITLE
Always a error when uses main_pipeline

### ISSUE THREAD

**Issue by cuic0808** [crisglav/eeg-pipeline#2]
Hi all,

I'm encountering an issue with my .bids data in discover-eeg, but always showed these error.
_Dot indexing is not supported for variables of this type.

Error in plot_badchannels (line 36)
chanlabels = {EEG(1).urchanlocs.labels};

Error in main_pipeline (line 207)
plot_badchannels(params,ALLEEG);_

What could be causing this issue? Thanks for your help!

**Comment by cuic0808** [comment]
Problem solved, use fieldtrip's bids convert function, and same matlab version.

**Comment by cuic0808** [comment]
Problem solved, use fieldtrip's bids convert function, and same matlab version.

**Comment by Nazmunkhan08** [comment]
Hey I am also getting error to run main pipeline file.
Error using jsondecode
JSON syntax error at line 9, column 20 (character 308): escape character '\U' is not valid.

Error in define_params (line 14)
params = jsondecode(str);

Error in main_pipeline (line 9)
params = define_params('params.json');
 
Could anyone be able to help me to rum the code?
