### ISSUE TITLE
Using individual MRIs

### ISSUE THREAD

**Issue by narunpat** [crisglav/eeg-pipeline#3]
Thank you for creating this EEG-BIDS pipeline. This looks promising! 

We are planning to apply the pipeline to the Healthy Brain Network dataset from the Child Mind Institute. This dataset provides individual MRI T1 images, which were processed using Freesurfer. 

Is there an instruction somewhere for us to use DISCOVER EEG with individual MRIs? 

I saw these two parameters:
"HeadModelPath" : "standard_bem.mat",
"SurfaceModelPath" : "surface_white_both.mat"

How do we create these .mat files from Freesurfer/Nifiti files? 

Also will the pipeline use electrode coordinates embedded in the BIDS files? See these coordinate files here
https://openneuro.org/datasets/ds004186/versions/2.0.0

**Comment by crisglav** [comment]
Dear narunpat,

Thanks for your interest and your question. At the moment it is not supported using individualized head models with the pipeline. Please refer to the fieldtrip documentation to create custom head models (https://www.fieldtriptoolbox.org/tutorial/sourcemodel/)
You will need to adjust the pipeline in accordance. 

Reading electrode coordinates from BIDS files is possible, setting the parameter 'BidsChanloc' to on. However I have not extensively tested this feature. Please note that I have just released a new version where all the parameters are documented now in the README.

Best,
Cristina
