### ISSUE TITLE
Epoch length and frequency res

### ISSUE THREAD

**Issue by sammymillard** [crisglav/eeg-pipeline#4]
Hello, thanks for making this pipeline!

I was hoping to change the epoch length and run your script. But it seems that you must specify a params.FreqRes that is higher (i.e. lower number) than the default for the params.EpochLength you set (i.e. 1/EpochLength). 

For example, if I set params.EpochLength to 5, and params.FreqRes to 0.2 or [ ], (i.e. the default that is calculated if left empty), then calling the function define_params.m does not work. I believe this is because the logical statements within define_params.m to check the params.Pad parameter do not work unless params.Pad has been specified manually or becomes set to 1/params.FreqRes at line 248 when the FreqRes has been assessed to be smaller than 1/EpochLength. The latter is the case for EpochLength of 2 and FreqRes of 0.1 as was set in your params_example.json.

I have set up a workaround for my self by commenting out the check for params.Pad and having no padding specified, but this might be something for you to look into. And of course, if you can't replicate the problem, let me know, as there might be other issues happening on my end if so :)

A small extra thing in relation to this, within your compute_power.m function line 12, you have cfg.pad = params.Padding, which I believe should be cfg.pad = params.Pad to match the params_example.json. 

Best wishes,
Sammy

**Comment by crisglav** [comment]
Dear Sammy,

Thank you for reporting the issues. I just fixed them and now it should work :)

Best,
Cristina
