### ISSUE TITLE
PAF by channel

### ISSUE THREAD

**Issue by sammymillard** [crisglav/eeg-pipeline#5]
Hello :)

I'm thinking of adapting your 'compute_peakfrequency' function to additionally output localmax and cog PAF values for each channel to complement the global PAF you have already. 

If this is something you already have let me know, otherwise I can share with you once I have it working and you can decide whether to have it in your software. 

Best,
Sammy

**Comment by crisglav** [comment]
Hi Sammy! That's of course an alternative to compute PAF. I hope you managed to do it.
