### ISSUE TITLE
Question about preprocessed data

### ISSUE THREAD

**Issue by eledau** [crisglav/eeg-pipeline#6]
Hello,
I am having problems understanding how to find the preprocessed data. I never used MatLab before so that's why I am confused. i need to access the preprocessed data inside the preprocessed folder but I see a .mat and .set files bot containing arrays (which I imagine are the data I am looking for). I need to further analyse the data on Python so which one of the two files contains the preprocessed data that I should use for my analysis? Or do they contain the same thing?
Thank you for your help!

**Comment by crisglav** [comment]
Both the eeglab .set files and the .mat files contain the preprocessed data (if the preprocessing was done successfully). .mat files are generated only when feature extraction is activated. They are generated as auxiliary files to accelerate the process of loading the data when computing the features.
