### ISSUE TITLE
How to use params_example_preproc_event.json to processing data include event

### ISSUE THREAD

**Issue by neurochenhe** [crisglav/eeg-pipeline#8]
Hi, Cristina,
I noticed that in the second version of the release you posted, there is a [params_example_preproc_event.json](https://github.com/crisglav/discover-eeg/blob/master/params_example_preproc_event.json) file，I wonder  to know how to use params_example_preproc_event.json to processing data include event.

Thanks!

**Comment by crisglav** [comment]
Hi,

The readme was updated with the preprocessing parameters for event-relate preprocessing. You can have a look there.

Best,
Cristina
